### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bitstormFA** [xnuohz/DeeperGCN-dgl#1]
Hi,

Many thanks for this very interesting implementation.
I would like to do some experiments with the code but I can't see a license information (please excuse if I overlooked something).
Could you please point me to the license information or add a license statement?

Best Regards

**Comment by xnuohz** [comment]
Hi,

The official example of deepergcn by dgl is [here](https://github.com/dmlc/dgl/tree/master/examples/pytorch/deepergcn), I think maybe you could use dgl's license?

Thanks:)

**Comment by bitstormFA** [comment]
Many thanks for pointing me to the dgl examples - I didn't see it
