### ISSUE TITLE
关于edge_encoder缺失的问题

### ISSUE THREAD

**Issue by wanghan0501** [xnuohz/DeeperGCN-dgl#2]
您好，学习了您的代码，发现代码要求输入的g必须在边上具备属性，想请教一下，如果输入的g没有属性，那么代码应该如何改进？

**Comment by xnuohz** [comment]
建议看一下dgl的文档里在message passing时如何只使用node的feature

**Comment by wanghan0501** [comment]
您的代码里要求必须有edge_encoder，这是不是意味着可以删掉？

**Comment by xnuohz** [comment]
是的
