### ISSUE TITLE
About ogbg_ppa.py

### ISSUE THREAD

**Issue by ycjing** [xnuohz/DeeperGCN-dgl#3]
Dear @xnuohz 

Thank you very much for the great code! When I run ogbg_ppa.py, it seemed that the memory (32GB) for loading the dataset will be exhausted, and the process got killed. Could I please ask if there is any solution to fix this issue? Many thanks!

Cheers,

**Comment by xnuohz** [comment]
Hi @ycjing sorry for delay reply. I recommend to use an instance with larger memory. But if the computing resource is limited, not sure these solutions can help you
- reduce batch size
- half precision / reduce embedding dimension
- neighbor sampling

**Comment by ycjing** [comment]
Dear @xnuohz 

Thank you sincerely for your response! I appreciate it. I will have a try.

Best regards,
